# Datasource temporal H2 en memoria con compatibilidad PostgreSQL
spring.datasource.url=jdbc:h2:mem:horariosdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configuración de Supabase (server-side)
# - Usa SERVICE_ROLE en el backend sólo si necesitas privilegios administrativos (rotar si fue expuesto)
supabase.url=https://gyddufkyfhxuvyvhiewp.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZGR1Zmt5Zmh4dXZ5dmhpZXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2OTM1NzEsImV4cCI6MjA3NzI2OTU3MX0.EH9dZQsqrbjYzRUUXAusj9ne7wrE5a-l3UtU--V2dpk
supabase.service-role=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZGR1Zmt5Zmh4dXZ5dmhpZXdwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTY5MzU3MSwiZXhwIjoyMDc3MjY5NTcxfQ.X8ASKCD77btSA01KBXn7-OG_xulio57RHcXowJaV63Q
supabase.access-token=sbp_bc0e83d89a22371bcc7b8731c255ebfb74ce66d2

# Puerto del servidor
server.port=8081
